#!/usr/bin/env ruby

require 'bundler/setup'
require 'alma_course_loader/cli/diff'

dsn = ENV['SENTRY_DSN']
unless dsn.nil? || dsn.empty?
  require 'raven'
  Raven.configure { |config| config.dsn = dsn }
end
AlmaCourseLoader::CLI::Diff.run